name: Build and Push 
 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
     
env: 
  REGISTRY: ghcr.io 
  IMAGE_NAME: ${{ github.repository }} 
  COMPARE_TAG: prod 
 
permissions: 
  contents: read 
  packages: write 
  pull-requests: write 
 
jobs: 
  docker_build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4 
 
      - name: Log in to the Container registry 
        uses: docker/login-action@v3 
        with: 
          registry: ${{ env.REGISTRY }} 
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }} 
 
      - name: Extract metadata (tags, labels) for Docker 
        id: meta 
        uses: docker/metadata-action@v5 
        with: 
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 
        labels: | 
          org.opencontainers.image.revision=${{ env.SHA }} 
        tags: | 
          type=ref,event=pull_request 
          type=semver,pattern=v{{version}} 
          type=sha,prefix=,suffix=,format=short 
           
      - name: Setup QEMU 
        uses: docker/setup-qemu-action@v3 
         
      - name: Setup Buildx 
        uses: docker/setup-buildx-action@v3 
 
      - name: Build and push Docker image 
        uses: docker/build-push-action@v5 
        with: 
          context: . 
          file: ./Dockerfile 
          push: true 
          platforms: linux/amd64,linux/arm64 
          sbom: true   
          tags: ${{ steps.meta.outputs.tags }} 
          labels: ${{ steps.meta.outputs.labels }} 
          cache-from: type=gha 
          cache-to: type=gha,mode=max 
 
  docker_scout_compare: 
    runs-on: ubuntu-latest 
    if: ${{ github.event_name == 'pull_request' }} 
    needs: 
      - docker_build 
    steps: 
      - name: Extract metadata (tags, labels) for Docker 
        id: meta 
        uses: docker/metadata-action@v5 
        with: 
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 
          tags: | 
            type=ref,event=pull_request 
 
      - name: Run Docker Scout to compare current image with the one in the registry 
        uses: docker/scout-action@master 
        with: 
          command: compare 
          image: ${{ steps.meta.outputs.tags }} 
          to: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMPARE_TAG }} 
          ignore-unchanged: true 
          only-severities: critical,high 
          token: ${{ secrets.DOCKER_PAT }} 
          write-comment: true 
          github-token: ${{ secrets.GITHUB_TOKEN }}   
           
      - name: Run Docker Scout to extract vulnerabilities from the image 
        uses: docker/scout-action@master 
        with: 
          command: cves 
          image: ${{ steps.meta.outputs.tags }} 
          sarif-file: scout.sarif 
          token: ${{ secrets.DOCKER_PAT }} 
 
      - name: Upload Docker Scout scan results to GitHub Security tab 
        uses: github/codeql-action/upload-sarif@v2 
        with: 
          sarif_file: scout.sarif 